image:
  repository: organizat-frontend
  tag: dev
  pullPolicy: IfNotPresent

env:
  BACKEND_API_BASE_URL: "http://organizat-backend.default.svc.cluster.local:8000/api"
  NEXT_PUBLIC_APP_URL: "http://organizat-frontend.local"
  NEXT_PUBLIC_USE_DEV_API: "true"
  NEXT_PUBLIC_DEV_BACKEND_URL: "http://organizat-backend.default.svc.cluster.local:8000/api"
  NEXT_PUBLIC_BACKEND_URL: "http://organizat-backend.default.svc.cluster.local:8000/api"
  GEMINI_API_KEY: "AIzaSyBOgja22GKmzeYyNeKfDsL1tBv4PYvnwuw"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: organizat-frontend.local
      paths:
        - path: /
          pathType: Prefix